#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Pageset
version:      1.01
version_from: lib/Data/Pageset.pm
installdirs:  site
requires:
    Test::More:                    0.1
    Data::Page:                    2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
